project:
  data_dir: data
  output_dir: outputs
  saved_models_dir: saved_models

dataset:
  name: jakartaresearch/semeval-absa
  config: restaurant
  eval_size: 0.2
  split_seed: 42
  test_split: validation

models:
  bert: bert-base-uncased
  transformer: FacebookAI/xlm-roberta-base
  generative_tokenizer: google/flan-t5-base
  generative: NUSTM/restaurant-t5-base

paths:
  lstm_extractor: saved_models/lstm_extractor
  lstm_sentiment: saved_models/lstm_sentiment
  transformer_extractor: saved_models/transformer_extractor
  transformer_sentiment: saved_models/transformer_sentiment
  generative: saved_models/generative
